# JEKYLL
exclude: [".gitignore", ".git", "config.rb", "package.json", "Gruntfile.js", "bower_components", ".travis.yml", "ai", "src", "VERSION", "LICENSE", "README.md", "icon.png", "node_modules"]

destination: ./_site

url: http://0.0.0.0:4000/
environment: development
description: Ink is a set of tools for quick development of web interfaces.
timezone: Europe/Lisbon

# SITE TITLE
title: Sapo Broker

# INK LATEST VERSION
version: 3.0.3

# URLS
repo_url: https://github.com/sapo/sapo-broker/
cdn_url: http://cdn.ink.sapo.pt/

# ASSETS PATHS
images_path: /sapo-broker/assets/img/
js_path: /sapo-broker/assets/js/
css_path: /sapo-broker/assets/css/

sections:

  - title: What is it?
    url: what-is-it
  - title: Documentation
    components:
      - title: Server
        topics:
          - title: Basic principles
            url: documentation
      - title: Clients
        topics:
          - title: C
            first: false
          - title: Java
          - title: PHP
          - title: Perl
          - title: Python
          - title: ruby
      - title: Security
        topics:
            - title: SSL
              first: false
              hash: true
            - title: Authentication
              hash: true
            - title: Authorization
              hash: true


releases:
  - 3.0.0
  - 2.3.2
  - 2.3.1
  - 2.3.0
  - 2.2.1
  - 2.2.0
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.1.0
  - 0.1.0

# ANALYTICS
analytics:
markdown: redcarpet
